#!/usr/bin/perl
# $Id: cvs_com,v 1.2 2003/10/03 00:11:35 sisoft Exp $
if(!-e "ChangeLog"){goto chng}
system("mcedit +666 x");
open(X,"x")||die("can't open 'x'-changes\n");
open(F,"TodayFixes")||die("can't open TodayFixes\n");
while(<F>) {
    if(/^\/\*/){$id=$_;next};
    if(/^---/){$fixes=$fixes?3:1;next}
    if(/^\./){$fixes=($fixes==1)?2:0;next}
    if($fixes==1){push(@fix,$_)}
    if($fixes==3){next}
    if(!$fixes){push(@txt,$_)}
}
open(F,">TodayFixes")||die("can't create TodayFixes\n");
print F "$id---\n";
while(<X>){print F $_} 
print F ".\nprevious:\n---\n";
foreach(@fix){print F $_}
print F ".\n";
foreach(@txt){print F $_}
close(X,F,T);
unlink("ChangeLog");
chng:
system("cvs2cl -F trunk --no-wrap -S");
unlink("ChangeLog.bak");
system("cvs com -F x");
if($?>>8){exit}
truncate("x",0);
