.TH QCC 8 "19 Oct 2003"
.SH NAME
qcc \- ncurses frontend for qico ftn mailer.
.SH SYNOPSIS
.B qcc
.RB [ \-nfhv ]
.SH DESCRIPTION
.B qcc
is a graphical ncurses-based frontend for qico ftn mailer.
.SH OPTIONS
.TP
.BI \-n
Start
.B qcc
in silent mode (without stupid beeeps).
.TP
.BI \-f
Run
.B qcc
force (without checking old IPC messages).
.TP
.BI \-h
Print help message.
.TP
.BI \-v
Print version message.
.SH SEE ALSO
qico(8), qctl(8)

qico homepage,
http://qico.sourceforge.net/
.SH AUTHORS
Stepan Pologov <sisoft@bk.ru>, and others:
 Cyril Margorin <cyrilm@tower.pp.ru> (official branch),
 Lev Serebryakov <lev@serebryakov.spb.ru> (up to 0.49.9),
 Pavel Kurnosoff <pqr@yasp.com> (up to 0.45pl3.1).
.SH "REPORTING BUGS"
Report bugs to <sisoft@bk.ru>
