#!/bin/sh
# script for tossing mail by sisoft\trg'2002
# $Id: tossing,v 1.1.1.1 2004/12/29 21:23:34 mitry Exp $

# netmail
find /var/spool/ftn/inb/*.[pP][kK][tT] >/dev/null 2>&1 &&
	/usr/local/bin/ftrack -c/etc/ftn/ftrack.conf

# fileecho
find /var/spool/ftn/inb/*.[tT][iI][cC] >/dev/null 2>&1 &&
	/usr/local/bin/htick toss

# echomail
find /var/spool/ftn/inb/*.[sSmMtTwWfF][aAuUoOeEhHrR][0-z] >/dev/null 2>&1 &&
	/usr/local/bin/hpt toss scan
