# $Id: x2c.awk,v 1.1.1.1 2004/12/29 21:23:34 mitry Exp $
BEGIN {
    C="qconf.c"; H="qconf.h"
    A="/* this file autogenerated from qconf.x, do not edit! */\n"
    print A "#include \"headers.h\"\n" >C
    print "cfgstr_t configtab[CFG_NNN+1]={" >C
    print A "#ifndef __QCONF_H__" >H
    print "#define __QCONF_H__\n" >H
    i=0
}

/^[^\#]/ {
    print "\t{\"" tolower($1) "\"," $2 "," $3 ",NULL," $4 "}," >C
    print "#define CFG_" toupper($1) "\t\t" i >H
    i++
}

END {
    print "\t{NULL,0,0,NULL,NULL}\n};" >C
    print "\n#define CFG_NNN\t\t" i >H
    print "extern cfgstr_t configtab[CFG_NNN+1];" >H
    print "\n#endif" >H
}
